// costofliving ? https://www.numbeo.com/cost-of-living/compare_cities.jsp?country1=Canada&country2=Canada&city1=Victoria%2C+BC&city2=Vancouver%2C+BC&tracking=getDispatchComparison

const ProgramList = [
	{
		id: 1,
		name: 'Computer Science',
		university: 'University of Victoria',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 25,
		deadline: '2024-12-01',
		url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg',
		cost: 22000 // Tuition + living costs for Victoria, BC (Bachelor's)
	},
	{
		id: 2,
		name: 'Business Administration',
		university: 'University of British Columbia',
		location: 'Vancouver, BC',
		degreeType: 'Bachelor',
		admissionRate: 35,
		deadline: '2024-11-15',
		url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg',
		cost: 25000 // Vancouver has higher living costs (Bachelor's)
	},
	{
		id: 3,
		name: 'Environmental Science',
		university: 'Thompson Rivers University',
		location: 'Kamloops, BC',
		degreeType: 'Bachelor',
		admissionRate: 40,
		deadline: '2024-10-30',
		url: 'https://universitystudy.ca/wp-content/uploads/2013/08/Thompson-Rivers_banner_web-960x.jpg',
		cost: 20000 // Lower living costs in Kamloops, BC (Bachelor's)
	},
	{
		id: 4,
		name: 'Mechanical Engineering',
		university: 'University of Calgary',
		location: 'Calgary, AB',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-12-05',
		url: 'https://ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba',
		cost: 23000 // Moderate costs for Calgary, AB (Bachelor's)
	},
	{
		id: 5,
		name: 'Psychology',
		university: 'University of Alberta',
		location: 'Edmonton, AB',
		degreeType: 'Bachelor',
		admissionRate: 45,
		deadline: '2024-11-30',
		url: 'https://images.shiksha.com/mediadata/images/1533646004phpFUNLK4.jpeg',
		cost: 22000 // Moderate costs for Edmonton, AB (Bachelor's)
	},
	/*  { 
                id: 6, 
                name: 'Law', 
                university: 'University of British Columbia', 
                location: 'Vancouver, BC', 
                degreeType: 'Master', 
                admissionRate: 20, 
                deadline: '2024-12-20', 
                url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg', 
                cost: 30000 // Higher cost for Master's in Vancouver, BC
        }, */
	{
		id: 7,
		name: 'Biology',
		university: 'Simon Fraser University',
		location: 'Burnaby, BC',
		degreeType: 'Bachelor',
		admissionRate: 50,
		deadline: '2024-11-25',
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_rwTmM_uiGLg5DXBmRPXg72gqQ8FpEq8Ig&s',
		cost: 24000 // Burnaby, BC, moderate cost (Bachelor's)
	},
	{
		id: 8,
		name: 'Environmental Engineering',
		university: 'University of Calgary',
		location: 'Calgary, AB',
		degreeType: 'Bachelor',
		admissionRate: 35,
		deadline: '2024-12-10',
		url: 'https://ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba',
		cost: 23000 // Calgary, AB (Bachelor's)
	},
	{
		id: 9,
		name: 'Nursing',
		university: 'University of British Columbia',
		location: 'Vancouver, BC',
		degreeType: 'Bachelor',
		admissionRate: 20,
		deadline: '2024-12-15',
		url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg',
		cost: 27000 // Nursing costs slightly higher in Vancouver, BC (Bachelor's)
	},
	{
		id: 10,
		name: 'Finance',
		university: 'University of Alberta',
		location: 'Edmonton, AB',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-11-20',
		url: 'https://images.shiksha.com/mediadata/images/1533646004phpFUNLK4.jpeg',
		cost: 22000 // Moderate costs for Edmonton, AB (Bachelor's)
	},
	{
		id: 11,
		name: 'Engineering Physics',
		university: 'University of Victoria',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 35,
		deadline: '2024-11-25',
		url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg',
		cost: 23000 // Higher for engineering program in Victoria, BC
	},
	{
		id: 12,
		name: 'Biochemistry',
		university: 'University of Calgary',
		location: 'Calgary, AB',
		degreeType: 'Bachelor',
		admissionRate: 40,
		deadline: '2024-12-10',
		url: 'https://ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba',
		cost: 23000 // Calgary, AB (Bachelor's)
	},
	{
		id: 13,
		name: 'Arts and Sciences',
		university: 'University of British Columbia Okanagan',
		location: 'Kelowna, BC',
		degreeType: 'Bachelor',
		admissionRate: 50,
		deadline: '2024-11-30',
		url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg',
		cost: 21000 // Kelowna is slightly cheaper (Bachelor's)
	},
	/* { 
                id: 14, 
                name: 'Computer Science', 
                university: 'University of Alberta', 
                location: 'Edmonton, AB', 
                degreeType: 'Master', 
                admissionRate: 30, 
                deadline: '2024-12-15', 
                url: 'https://images.shiksha.com/mediadata/images/1533646004phpFUNLK4.jpeg', 
                cost: 28000 // Higher cost for Master's program in Edmonton, AB
        }, */
	{
		id: 15,
		name: 'Environmental Studies',
		university: 'Simon Fraser University',
		location: 'Burnaby, BC',
		degreeType: 'Bachelor',
		admissionRate: 45,
		deadline: '2024-11-20',
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_rwTmM_uiGLg5DXBmRPXg72gqQ8FpEq8Ig&s',
		cost: 24000 // Burnaby, BC, moderate cost
	},
	{
		id: 16,
		name: 'Political Science',
		university: 'University of Victoria',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 45,
		deadline: '2024-12-15',
		url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg',
		cost: 22000 // Victoria, BC, moderate cost
	},
	{
		id: 17,
		name: 'Sociology',
		university: 'University of Calgary',
		location: 'Calgary, AB',
		degreeType: 'Bachelor',
		admissionRate: 25,
		deadline: '2024-11-20',
		url: 'https://www.ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba',
		cost: 23000 // Calgary, AB, moderate cost
	},
	{
		id: 18,
		name: 'Mathematics',
		university: 'University of British Columbia Okanagan',
		location: 'Kelowna, BC',
		degreeType: 'Bachelor',
		admissionRate: 35,
		deadline: '2024-12-05',
		url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg',
		cost: 21000 // Kelowna, BC, slightly lower cost
	},
	{
		id: 19,
		name: 'Economics',
		university: 'University of Alberta',
		location: 'Edmonton, AB',
		degreeType: 'Bachelor',
		admissionRate: 40,
		deadline: '2024-11-25',
		url: 'https://images.shiksha.com/mediadata/images/1533646004phpFUNLK4.jpeg',
		cost: 22000 // Edmonton, AB, moderate cost
	},
	{
		id: 20,
		name: 'Environmental Engineering',
		university: 'University of British Columbia',
		location: 'Vancouver, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-11-30',
		url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg',
		cost: 27000 // Vancouver, BC, higher cost
	},
	{
		id: 21,
		name: 'Film Studies',
		university: 'Simon Fraser University',
		location: 'Burnaby, BC',
		degreeType: 'Bachelor',
		admissionRate: 45,
		deadline: '2024-12-15',
		url: 'https://www.sfu.ca/content/sfu/sfucommunity/woodwards/photo-gallery/jcr:content/main_content/image_0.img.960.auto.jpg/1634310628497.jpg',
		cost: 24000 // Burnaby, BC, moderate cost
	},
	{
		id: 22,
		name: 'History',
		university: 'University of Calgary',
		location: 'Calgary, AB',
		degreeType: 'Bachelor',
		admissionRate: 25,
		deadline: '2024-11-20',
		url: 'https://www.ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba',
		cost: 23000 // Calgary, AB, moderate cost
	},
	{
		id: 23,
		name: 'Philosophy',
		university: 'University of British Columbia Okanagan',
		location: 'Kelowna, BC',
		degreeType: 'Bachelor',
		admissionRate: 35,
		deadline: '2024-12-05',
		url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg',
		cost: 21000 // Kelowna, BC, slightly lower cost
	},
	{
		id: 24,
		name: 'Education',
		university: 'University of Alberta',
		location: 'Edmonton, AB',
		degreeType: 'Bachelor',
		admissionRate: 40,
		deadline: '2024-11-25',
		url: 'https://images.shiksha.com/mediadata/images/1533646004phpFUNLK4.jpeg',
		cost: 22000 // Edmonton, AB, moderate cost
	},
	{
		id: 25,
		name: 'Geography',
		university: 'University of British Columbia',
		location: 'Vancouver, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-11-30',
		url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg',
		cost: 27000 // Vancouver, BC, higher cost
	},
	{
		id: 26,
		name: 'Indigenous Studies',
		university: 'University of Victoria',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 40,
		deadline: '2024-12-05',
		url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg',
		cost: 22000 // Victoria, BC, moderate cost
	},
	{
		id: 27,
		name: 'Computer Science',
		university: 'University of Northern British Columbia',
		location: 'Prince George, BC',
		degreeType: 'Bachelor',
		admissionRate: 25,
		deadline: '2024-12-01',
		url: 'https://www.unbc.ca/sites/default/files/styles/listed_image/public/featured-link/dsc2878crop.jpg.webp?itok=rzZEleNT',
		cost: 20000 // Prince George, BC, lower cost
	},
	{
		id: 28,
		name: 'Anthropology',
		university: 'University of British Columbia Okanagan',
		location: 'Kelowna, BC',
		degreeType: 'Bachelor',
		admissionRate: 35,
		deadline: '2024-12-05',
		url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg',
		cost: 21000 // Kelowna, BC, slightly lower cost
	},
	{
		id: 29,
		name: 'Sustainable Energy Engineering',
		university: 'Simon Fraser University',
		location: 'Burnaby, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-12-01',
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_rwTmM_uiGLg5DXBmRPXg72gqQ8FpEq8Ig&s',
		cost: 24000 // Burnaby, BC, moderate cost
	},
	{
		id: 30,
		name: 'Physics',
		university: 'University of Calgary',
		location: 'Calgary, AB',
		degreeType: 'Bachelor',
		admissionRate: 45,
		deadline: '2024-11-25',
		url: 'https://www.ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba',
		cost: 23000 // Calgary, AB, moderate cost
	},
	/* { 
                id: 31, 
                name: 'Architecture', 
                university: 'University of British Columbia', 
                location: 'Vancouver, BC', 
                degreeType: 'Master', 
                admissionRate: 25, 
                deadline: '2025-01-20', 
                url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg', 
                cost: 32000 // Higher cost for Master's in Vancouver, BC
        }, */
	{
		id: 32,
		name: 'Human Resource Management',
		university: 'University of Alberta',
		location: 'Edmonton, AB',
		degreeType: 'Bachelor',
		admissionRate: 40,
		deadline: '2024-12-05',
		url: 'https://images.shiksha.com/mediadata/images/1533646004phpFUNLK4.jpeg',
		cost: 22000 // Moderate cost for Bachelor's in Edmonton, AB
	},
	/* { 
                id: 33, 
                name: 'Environmental Science', 
                university: 'University of Calgary', 
                location: 'Calgary, AB', 
                degreeType: 'Master', 
                admissionRate: 30, 
                deadline: '2025-01-10', 
                url: 'https://www.ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba', 
                cost: 30000 // Higher cost for Master's in Calgary, AB
        }, 
        { 
                id: 34, 
                name: 'Political Economy', 
                university: 'University of Victoria', 
                location: 'Victoria, BC', 
                degreeType: 'Master', 
                admissionRate: 20, 
                deadline: '2025-01-30', 
                url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg', 
                cost: 28000 // Higher cost for Master's in Victoria, BC
        }, */
	{
		id: 35,
		name: 'Public Relations',
		university: 'Royal Roads University',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 50,
		deadline: '2024-11-30',
		url: 'https://cdn.prod.website-files.com/667c59abb9df9789d17407a6/667dd6863400fe779b562af4_UNIVERSITY-GUIDEBOOK-2022-ROYAL-ROADS-01-1.jpeg',
		cost: 21000 // Lower cost for Bachelor's in Victoria, BC
	},
	/* { 
                id: 36, 
                name: 'Data Science', 
                university: 'University of British Columbia', 
                location: 'Vancouver, BC', 
                degreeType: 'Master', 
                admissionRate: 15, 
                deadline: '2025-02-15', 
                url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg', 
                cost: 33000 // High cost for Data Science Master's in Vancouver, BC
        }, */
	{
		id: 37,
		name: 'Sociology',
		university: 'University of Northern British Columbia',
		location: 'Prince George, BC',
		degreeType: 'Bachelor',
		admissionRate: 40,
		deadline: '2024-12-10',
		url: 'https://www.unbc.ca/sites/default/files/styles/listed_image/public/featured-link/dsc2878crop.jpg.webp?itok=rzZEleNT',
		cost: 20000 // Lower cost for Bachelor's in Prince George, BC
	},
	{
		id: 38,
		name: 'Nursing',
		university: 'Mount Royal University',
		location: 'Calgary, AB',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-11-15',
		url: 'https://www.unbc.ca/sites/default/files/styles/listed_image/public/featured-link/dsc2878crop.jpg.webp?itok=rzZEleNT',
		cost: 23000 // Moderate cost for Nursing Bachelor's in Calgary, AB
	},
	{
		id: 39,
		name: 'Criminology',
		university: 'Simon Fraser University',
		location: 'Burnaby, BC',
		degreeType: 'Bachelor',
		admissionRate: 35,
		deadline: '2024-12-01',
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_rwTmM_uiGLg5DXBmRPXg72gqQ8FpEq8Ig&s',
		cost: 24000 // Moderate cost for Bachelor's in Burnaby, BC
	},
	/* { 
                id: 40, 
                name: 'Environmental Design', 
                university: 'University of Calgary', 
                location: 'Calgary, AB', 
                degreeType: 'Master', 
                admissionRate: 20, 
                deadline: '2025-01-25', 
                url: 'https://www.ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba', 
                cost: 31000 // Higher cost for Environmental Design Master's in Calgary, AB
        }, */
	{
		id: 41,
		name: 'Agriculture',
		university: 'University of British Columbia',
		location: 'Vancouver, BC',
		degreeType: 'Bachelor',
		admissionRate: 25,
		deadline: '2024-11-20',
		url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg',
		cost: 27000 // Higher cost for Bachelor's in Vancouver, BC
	},
	{
		id: 42,
		name: 'Graphic Design',
		university: 'Emily Carr University of Art + Design',
		location: 'Vancouver, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-12-01',
		url: 'https://dsai.ca/wp-content/uploads/Emily-Carr-Hero.jpg',
		cost: 26000 // Moderate cost for Bachelor's in Vancouver, BC
	},
	{
		id: 43,
		name: 'Music Composition',
		university: 'University of Alberta',
		location: 'Edmonton, AB',
		degreeType: 'Bachelor',
		admissionRate: 40,
		deadline: '2024-11-30',
		url: 'https://images.shiksha.com/mediadata/images/1533646004phpFUNLK4.jpeg',
		cost: 22000 // Moderate cost for Bachelor's in Edmonton, AB
	},
	{
		id: 44,
		name: 'Linguistics',
		university: 'University of Victoria',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 35,
		deadline: '2024-12-10',
		url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg',
		cost: 22000 // Moderate cost for Bachelor's in Victoria, BC
	},
	

	//Van's pseudo data
	{
		id: 45,
		name: 'Computer Science',
		university: 'University of British Columbia Vancouver',
		location: 'Vancouver, BC',
		degreeType: 'Bachelor',
		admissionRate: 20,
		deadline: '2024-11-15',
		url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg',
		cost: 30000 // Vancouver has higher living costs (Bachelor's)
	},
	{
		id: 46,
		name: 'Psychology',
		university: 'University of British Columbia Vancouver',
		location: 'Vancouver, BC',
		degreeType: 'Bachelor',
		admissionRate: 50,
		deadline: '2024-10-20',
		url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg',
		cost: 27000 // Vancouver has higher living costs (Bachelor's)
	},
	{
		id: 47,
		name: 'Biology',
		university: 'University of British Columbia Vancouver',
		location: 'Vancouver, BC',
		degreeType: 'Bachelor',
		admissionRate: 40,
		deadline: '2024-11-20',
		url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg',
		cost: 27000 // Vancouver has higher living costs (Bachelor's)
	},
	{
		id: 48,
		name: 'Economics',
		university: 'University of British Columbia Vancouver',
		location: 'Vancouver, BC',
		degreeType: 'Bachelor',
		admissionRate: 35,
		deadline: '2024-11-15',
		url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg',
		cost: 30000 // Vancouver has higher living costs (Bachelor's)
	},
	{
		id: 49,
		name: 'Education',
		university: 'University of British Columbia Vancouver',
		location: 'Vancouver, BC',
		degreeType: 'Bachelor',
		admissionRate: 40,
		deadline: '2024-12-00',
		url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg',
		cost: 18000 // Vancouver has higher living costs (Bachelor's)
	},
	{
		id: 50,
		name: 'Business Administration',
		university: 'Simon Fraser University',
		location: 'Burnaby, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-11-21',
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_rwTmM_uiGLg5DXBmRPXg72gqQ8FpEq8Ig&s',
		cost: 28000 // Burnaby, BC, moderate cost (Bachelor's)
	},
	{
		id: 51,
		name: 'Nursing',
		university: 'Simon Fraser University',
		location: 'Burnaby, BC',
		degreeType: 'Bachelor',
		admissionRate: 50,
		deadline: '2024-11-25',
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_rwTmM_uiGLg5DXBmRPXg72gqQ8FpEq8Ig&s',
		cost: 60000 // Burnaby, BC, moderate cost (Bachelor's)
	},
	{
		id: 52,
		name: 'Computer Science',
		university: 'Simon Fraser University',
		location: 'Burnaby, BC',
		degreeType: 'Bachelor',
		admissionRate: 41,
		deadline: '2024-11-25',
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_rwTmM_uiGLg5DXBmRPXg72gqQ8FpEq8Ig&s',
		cost: 24820 // Burnaby, BC, moderate cost (Bachelor's)
	},
	{
		id: 53,
		name: 'Psychology',
		university: 'Simon Fraser University',
		location: 'Burnaby, BC',
		degreeType: 'Bachelor',
		admissionRate: 35,
		deadline: '2024-11-25',
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_rwTmM_uiGLg5DXBmRPXg72gqQ8FpEq8Ig&s',
		cost: 28000 // Burnaby, BC, moderate cost (Bachelor's)
	},
	{
		id: 54,
		name: 'Electrical Engineering',
		university: 'Simon Fraser University',
		location: 'Burnaby, BC',
		degreeType: 'Bachelor',
		admissionRate: 41,
		deadline: '2024-11-25',
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_rwTmM_uiGLg5DXBmRPXg72gqQ8FpEq8Ig&s',
		cost: 28000 // Burnaby, BC, moderate cost (Bachelor's)
	},
	{
		id: 55,
		name: 'Economics',
		university: 'Simon Fraser University',
		location: 'Burnaby, BC',
		degreeType: 'Bachelor',
		admissionRate: 50,
		deadline: '2024-11-25',
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_rwTmM_uiGLg5DXBmRPXg72gqQ8FpEq8Ig&s',
		cost: 30000 // Burnaby, BC, moderate cost (Bachelor's)
	},
	{
		id: 56,
		name: 'Education',
		university: 'Simon Fraser University',
		location: 'Burnaby, BC',
		degreeType: 'Bachelor',
		admissionRate: 45,
		deadline: '2024-11-25',
		url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_rwTmM_uiGLg5DXBmRPXg72gqQ8FpEq8Ig&s',
		cost: 18000 // Burnaby, BC, moderate cost (Bachelor's)
	},
	{
		id: 57,
		name: 'Business Administration',
		university: 'University of Victoria',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-12-17',
		url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg',
		cost: 28000 // Tuition + living costs for Victoria, BC (Bachelor's)
	},
	{
		id: 58,
		name: 'Nursing',
		university: 'University of Victoria',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 25,
		deadline: '2024-12-23',
		url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg',
		cost: 26000 // Tuition + living costs for Victoria, BC (Bachelor's)
	},
	{
		id: 59,
		name: 'Psychology',
		university: 'University of Victoria',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 25,
		deadline: '2024-12-15',
		url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg',
		cost: 26000 // Tuition + living costs for Victoria, BC (Bachelor's)
	},
	{
		id: 60,
		name: 'Biology',
		university: 'University of Victoria',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 25,
		deadline: '2024-12-17',
		url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg',
		cost: 32000 // Tuition + living costs for Victoria, BC (Bachelor's)
	},
	{
		id: 61,
		name: 'Civil Engineering',
		university: 'University of Victoria',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 25,
		deadline: '2024-12-17',
		url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg',
		cost: 35000 // Tuition + living costs for Victoria, BC (Bachelor's)
	},
	{
		id: 62,
		name: 'Economics',
		university: 'University of Victoria',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 25,
		deadline: '2024-12-10',
		url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg',
		cost: 24000 // Tuition + living costs for Victoria, BC (Bachelor's)
	},
	{
		id: 63,
		name: 'Education',
		university: 'University of Victoria',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 25,
		deadline: '2024-12-17',
		url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg',
		cost: 28000 // Tuition + living costs for Victoria, BC (Bachelor's)
	},
	{
		id: 64,
		name: 'Business Administration',
		university: 'Thompson Rivers University',
		location: 'Kamloops, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-10-30',
		url: 'https://universitystudy.ca/wp-content/uploads/2013/08/Thompson-Rivers_banner_web-960x.jpg',
		cost: 27000 // Lower living costs in Kamloops, BC (Bachelor's)
	},
	{
		id: 65,
		name: 'Nursing',
		university: 'Thompson Rivers University',
		location: 'Kamloops, BC',
		degreeType: 'Bachelor',
		admissionRate: 45,
		deadline: '2024-10-30',
		url: 'https://universitystudy.ca/wp-content/uploads/2013/08/Thompson-Rivers_banner_web-960x.jpg',
		cost: 30000 // Lower living costs in Kamloops, BC (Bachelor's)
	},
	{
		id: 66,
		name: 'Computer Science',
		university: 'Thompson Rivers University',
		location: 'Kamloops, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-10-30',
		url: 'https://universitystudy.ca/wp-content/uploads/2013/08/Thompson-Rivers_banner_web-960x.jpg',
		cost: 28000 // Lower living costs in Kamloops, BC (Bachelor's)
	},
	{
		id: 67,
		name: 'Psychology',
		university: 'Thompson Rivers University',
		location: 'Kamloops, BC',
		degreeType: 'Bachelor',
		admissionRate: 35,
		deadline: '2024-10-30',
		url: 'https://universitystudy.ca/wp-content/uploads/2013/08/Thompson-Rivers_banner_web-960x.jpg',
		cost: 26000 // Lower living costs in Kamloops, BC (Bachelor's)
	},
	{
		id: 68,
		name: 'Biology',
		university: 'Thompson Rivers University',
		location: 'Kamloops, BC',
		degreeType: 'Bachelor',
		admissionRate: 20,
		deadline: '2024-10-30',
		url: 'https://universitystudy.ca/wp-content/uploads/2013/08/Thompson-Rivers_banner_web-960x.jpg',
		cost: 32000 // Lower living costs in Kamloops, BC (Bachelor's)
	},
	{
		id: 69,
		name: 'Civil Engineering',
		university: 'Thompson Rivers University',
		location: 'Kamloops, BC',
		degreeType: 'Bachelor',
		admissionRate: 29,
		deadline: '2024-10-30',
		url: 'https://universitystudy.ca/wp-content/uploads/2013/08/Thompson-Rivers_banner_web-960x.jpg',
		cost: 28000 // Lower living costs in Kamloops, BC (Bachelor's)
	},
	{
		id: 70,
		name: 'Economics',
		university: 'Thompson Rivers University',
		location: 'Kamloops, BC',
		degreeType: 'Bachelor',
		admissionRate: 35,
		deadline: '2024-10-30',
		url: 'https://universitystudy.ca/wp-content/uploads/2013/08/Thompson-Rivers_banner_web-960x.jpg',
		cost: 28000 // Lower living costs in Kamloops, BC (Bachelor's)
	},
	{
		id: 71,
		name: 'Education',
		university: 'Thompson Rivers University',
		location: 'Kamloops, BC',
		degreeType: 'Bachelor',
		admissionRate: 29,
		deadline: '2024-10-30',
		url: 'https://universitystudy.ca/wp-content/uploads/2013/08/Thompson-Rivers_banner_web-960x.jpg',
		cost: 18000 // Lower living costs in Kamloops, BC (Bachelor's)
	},
	{
		id: 72,
		name: 'Computer Science',
		university: 'University of Northern British Columbia',
		location: 'Prince George, BC',
		degreeType: 'Bachelor',
		admissionRate: 25,
		deadline: '2024-12-01',
		url: 'https://www.unbc.ca/sites/default/files/styles/listed_image/public/featured-link/dsc2878crop.jpg.webp?itok=rzZEleNT',
		cost: 20000 // Prince George, BC, lower cost
	},
	{
		id: 73,
		name: 'Business Administration',
		university: 'University of Northern British Columbia',
		location: 'Prince George, BC',
		degreeType: 'Bachelor',
		admissionRate: 28,
		deadline: '2024-12-01',
		url: 'https://www.unbc.ca/sites/default/files/styles/listed_image/public/featured-link/dsc2878crop.jpg.webp?itok=rzZEleNT',
		cost: 20000 // Prince George, BC, lower cost
	},
	{
		id: 74,
		name: 'Nursing',
		university: 'University of Northern British Columbia',
		location: 'Prince George, BC',
		degreeType: 'Bachelor',
		admissionRate: 20,
		deadline: '2024-12-01',
		url: 'https://www.unbc.ca/sites/default/files/styles/listed_image/public/featured-link/dsc2878crop.jpg.webp?itok=rzZEleNT',
		cost: 32000 // Prince George, BC, lower cost
	},
	{
		id: 75,
		name: 'Psychology',
		university: 'University of Northern British Columbia',
		location: 'Prince George, BC',
		degreeType: 'Bachelor',
		admissionRate: 40,
		deadline: '2024-12-01',
		url: 'https://www.unbc.ca/sites/default/files/styles/listed_image/public/featured-link/dsc2878crop.jpg.webp?itok=rzZEleNT',
		cost: 27000 // Prince George, BC, lower cost
	},
	{
		id: 76,
		name: 'Biology',
		university: 'University of Northern British Columbia',
		location: 'Prince George, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-12-01',
		url: 'https://www.unbc.ca/sites/default/files/styles/listed_image/public/featured-link/dsc2878crop.jpg.webp?itok=rzZEleNT',
		cost: 27000 // Prince George, BC, lower cost
	},
	{
		id: 77,
		name: 'Electrical Engineering',
		university: 'University of Northern British Columbia',
		location: 'Prince George, BC',
		degreeType: 'Bachelor',
		admissionRate: 20,
		deadline: '2024-12-01',
		url: 'https://www.unbc.ca/sites/default/files/styles/listed_image/public/featured-link/dsc2878crop.jpg.webp?itok=rzZEleNT',
		cost: 22000 // Prince George, BC, lower cost
	},
	{
		id: 78,
		name: 'Economics',
		university: 'University of Northern British Columbia',
		location: 'Prince George, BC',
		degreeType: 'Bachelor',
		admissionRate: 35,
		deadline: '2024-12-01',
		url: 'https://www.unbc.ca/sites/default/files/styles/listed_image/public/featured-link/dsc2878crop.jpg.webp?itok=rzZEleNT',
		cost: 30000 // Prince George, BC, lower cost
	},
	{
		id: 79,
		name: 'Education',
		university: 'University of Northern British Columbia',
		location: 'Prince George, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-12-01',
		url: 'https://www.unbc.ca/sites/default/files/styles/listed_image/public/featured-link/dsc2878crop.jpg.webp?itok=rzZEleNT',
		cost: 28000 // Prince George, BC, lower cost
	},
	{
		id: 80,
		name: 'Business Administration',
		university: 'Royal Roads University',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-11-30',
		url: 'https://cdn.prod.website-files.com/667c59abb9df9789d17407a6/667dd6863400fe779b562af4_UNIVERSITY-GUIDEBOOK-2022-ROYAL-ROADS-01-1.jpeg',
		cost: 28000 // Lower cost for Bachelor's in Victoria, BC
	},
	{
		id: 81,
		name: 'Nursing',
		university: 'Royal Roads University',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 20,
		deadline: '2024-11-30',
		url: 'https://cdn.prod.website-files.com/667c59abb9df9789d17407a6/667dd6863400fe779b562af4_UNIVERSITY-GUIDEBOOK-2022-ROYAL-ROADS-01-1.jpeg',
		cost: 31000 // Lower cost for Bachelor's in Victoria, BC
	},
	{
		id: 82,
		name: 'Computer Science',
		university: 'Royal Roads University',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-11-30',
		url: 'https://cdn.prod.website-files.com/667c59abb9df9789d17407a6/667dd6863400fe779b562af4_UNIVERSITY-GUIDEBOOK-2022-ROYAL-ROADS-01-1.jpeg',
		cost: 27000 // Lower cost for Bachelor's in Victoria, BC
	},
	{
		id: 83,
		name: 'Psychology',
		university: 'Royal Roads University',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 50,
		deadline: '2024-11-30',
		url: 'https://cdn.prod.website-files.com/667c59abb9df9789d17407a6/667dd6863400fe779b562af4_UNIVERSITY-GUIDEBOOK-2022-ROYAL-ROADS-01-1.jpeg',
		cost: 28000 // Lower cost for Bachelor's in Victoria, BC
	},
	{
		id: 84,
		name: 'Biology',
		university: 'Royal Roads University',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 52,
		deadline: '2024-11-30',
		url: 'https://cdn.prod.website-files.com/667c59abb9df9789d17407a6/667dd6863400fe779b562af4_UNIVERSITY-GUIDEBOOK-2022-ROYAL-ROADS-01-1.jpeg',
		cost: 24000 // Lower cost for Bachelor's in Victoria, BC
	},
	{
		id: 85,
		name: 'Mechanical Engineering',
		university: 'Royal Roads University',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-11-30',
		url: 'https://cdn.prod.website-files.com/667c59abb9df9789d17407a6/667dd6863400fe779b562af4_UNIVERSITY-GUIDEBOOK-2022-ROYAL-ROADS-01-1.jpeg',
		cost: 27000 // Lower cost for Bachelor's in Victoria, BC
	},
	{
		id: 86,
		name: 'Economics',
		university: 'Royal Roads University',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 20,
		deadline: '2024-11-30',
		url: 'https://cdn.prod.website-files.com/667c59abb9df9789d17407a6/667dd6863400fe779b562af4_UNIVERSITY-GUIDEBOOK-2022-ROYAL-ROADS-01-1.jpeg',
		cost: 31000 // Lower cost for Bachelor's in Victoria, BC
	},
	{
		id: 87,
		name: 'Education',
		university: 'Royal Roads University',
		location: 'Victoria, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-11-30',
		url: 'https://cdn.prod.website-files.com/667c59abb9df9789d17407a6/667dd6863400fe779b562af4_UNIVERSITY-GUIDEBOOK-2022-ROYAL-ROADS-01-1.jpeg',
		cost: 19000 // Lower cost for Bachelor's in Victoria, BC
	},
	{
		id: 88,
		name: 'Business Administration',
		university: 'University of Alberta',
		location: 'Edmonton, AB',
		degreeType: 'Bachelor',
		admissionRate: 35,
		deadline: '2024-11-30',
		url: 'https://images.shiksha.com/mediadata/images/1533646004phpFUNLK4.jpeg',
		cost: 22000 // Moderate costs for Edmonton, AB (Bachelor's)
	},
	{
		id: 89,
		name: 'Business Administration',
		university: 'University of British Columbia Okanagan',
		location: 'Kelowna, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-12-30',
		url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg',
		cost: 27000 // Kelowna is slightly cheaper (Bachelor's)
	},
	{
		id: 90,
		name: 'Nursing',
		university: 'University of British Columbia Okanagan',
		location: 'Kelowna, BC',
		degreeType: 'Bachelor',
		admissionRate: 45,
		deadline: '2024-11-30',
		url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg',
		cost: 29000 // Kelowna is slightly cheaper (Bachelor's)
	},
	{
		id: 91,
		name: 'Computer Science',
		university: 'University of British Columbia Okanagan',
		location: 'Kelowna, BC',
		degreeType: 'Bachelor',
		admissionRate: 20,
		deadline: '2024-11-17',
		url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg',
		cost: 30000 // Kelowna is slightly cheaper (Bachelor's)
	},
	{
		id: 92,
		name: 'Psychology',
		university: 'University of British Columbia Okanagan',
		location: 'Kelowna, BC',
		degreeType: 'Bachelor',
		admissionRate: 20,
		deadline: '2024-11-30',
		url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg',
		cost: 24000 // Kelowna is slightly cheaper (Bachelor's)
	},
	{
		id: 93,
		name: 'Biology',
		university: 'University of British Columbia Okanagan',
		location: 'Kelowna, BC',
		degreeType: 'Bachelor',
		admissionRate: 25,
		deadline: '2024-11-30',
		url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg',
		cost: 29000 // Kelowna is slightly cheaper (Bachelor's)
	},
	{
		id: 94,
		name: 'Electrical Engineering',
		university: 'University of British Columbia Okanagan',
		location: 'Kelowna, BC',
		degreeType: 'Bachelor',
		admissionRate: 30,
		deadline: '2024-11-30',
		url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg',
		cost: 27000 // Kelowna is slightly cheaper (Bachelor's)
	},
	{
		id: 95,
		name: 'Economics',
		university: 'University of British Columbia Okanagan',
		location: 'Kelowna, BC',
		degreeType: 'Bachelor',
		admissionRate: 25,
		deadline: '2024-11-30',
		url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg',
		cost: 24000 // Kelowna is slightly cheaper (Bachelor's)
	},
	{
		id: 96,
		name: 'Education',
		university: 'University of British Columbia Okanagan',
		location: 'Kelowna, BC',
		degreeType: 'Bachelor',
		admissionRate: 31,
		deadline: '2024-11-30',
		url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg',
		cost: 24000 // Kelowna is slightly cheaper (Bachelor's)
	},
	{
		id: 97,
		name: 'Business Administration',
		university: 'Kwantlen Polytechnic University',
		location: 'Surrey, BC',
		degreeType: 'Bachelor',
		admissionRate: 33,
		deadline: '2024-11-30',
		url: 'https://www.kpu.ca/sites/default/files/Summer_2024_reg.png',
		cost: 35000 // Kelowna is slightly cheaper (Bachelor's)
	},
	{
		id: 98,
		name: 'Nursing',
		university: 'Kwantlen Polytechnic University',
		location: 'Surrey, BC',
		degreeType: 'Bachelor',
		admissionRate: 33,
		deadline: '2024-12-30',
		url: 'https://www.kpu.ca/sites/default/files/Summer_2024_reg.png',
		cost: 32000 // Kelowna is slightly cheaper (Bachelor's)
	},
	{
		id: 99,
		name: 'Computer Science',
		university: 'Kwantlen Polytechnic University',
		location: 'Surrey, BC',
		degreeType: 'Bachelor',
		admissionRate: 20,
		deadline: '2024-11-30',
		url: 'https://www.kpu.ca/sites/default/files/Summer_2024_reg.png',
		cost: 30000 // Kelowna is slightly cheaper (Bachelor's)
	},
	{
		id: 100,
		name: 'Psychology',
		university: 'Kwantlen Polytechnic University',
		location: 'Surrey, BC',
		degreeType: 'Bachelor',
		admissionRate: 33,
		deadline: '2024-11-30',
		url: 'https://www.kpu.ca/sites/default/files/Summer_2024_reg.png',
		cost: 32000 // Kelowna is slightly cheaper (Bachelor's)
	},
	{
		id: 101,
		name: 'Mechanical Engineering',
		university: 'Kwantlen Polytechnic University',
		location: 'Surrey, BC',
		degreeType: 'Bachelor',
		admissionRate: 33,
		deadline: '2024-11-30',
		url: 'https://www.kpu.ca/sites/default/files/Summer_2024_reg.png',
		cost: 35000 // Kelowna is slightly cheaper (Bachelor's)
	},
	{
		id: 102,
		name: 'Economics',
		university: 'Kwantlen Polytechnic University',
		location: 'Surrey, BC',
		degreeType: 'Bachelor',
		admissionRate: 33,
		deadline: '2024-11-30',
		url: 'https://www.kpu.ca/sites/default/files/Summer_2024_reg.png',
		cost: 37000 // Kelowna is slightly cheaper (Bachelor's)
	},
	{
		id: 103,
		name: 'Education',
		university: 'Kwantlen Polytechnic University',
		location: 'Surrey, BC',
		degreeType: 'Bachelor',
		admissionRate: 33,
		deadline: '2024-11-29',
		url: 'https://www.kpu.ca/sites/default/files/Summer_2024_reg.png',
		cost: 10000 // Kelowna is slightly cheaper (Bachelor's)
	},
	{
		id: 104,
		name: "Business Administration",
		university: "MacEwan University",
		location: "Edmonton, AB",
		degreeType: "Bachelor",
		admissionRate: 33,
		deadline: "2024-11-29",
		url: "https://www.macewan.ca/business-administration/apply.png",
		cost: 10000
	},
	{
		id: 105,
		name: "Nursing",
		university: "MacEwan University",
		location: "Edmonton, AB",
		degreeType: "Bachelor",
		admissionRate: 20,
		deadline: "2024-12-15",
		url: "https://www.macewan.ca/nursing/apply.png",
		cost: 11000
	},
	{
		id: 106,
		name: "Computer Science",
		university: "MacEwan University",
		location: "Edmonton, AB",
		degreeType: "Bachelor",
		admissionRate: 45,
		deadline: "2024-11-30",
		url: "https://www.macewan.ca/computerscience/admissions.png",
		cost: 12000
	},
	{
		id: 107,
		name: "Psychology",
		university: "MacEwan University",
		location: "Edmonton, AB",
		degreeType: "Bachelor",
		admissionRate: 50,
		deadline: "2025-01-20",
		url: "https://www.macewan.ca/psychology/apply.png",
		cost: 9000
	},
	{
		id: 108,
		name: "Biology",
		university: "MacEwan University",
		location: "Edmonton, AB",
		degreeType: "Bachelor",
		admissionRate: 30,
		deadline: "2024-12-10",
		url: "https://www.macewan.ca/biology/admissions.png",
		cost: 10500
	},
	{
		id: 109,
		name: "Mechanical Engineering",
		university: "MacEwan University",
		location: "Edmonton, AB",
		degreeType: "Bachelor",
		admissionRate: 25,
		deadline: "2025-01-05",
		url: "https://www.macewan.ca/engineering/apply.png",
		cost: 13000
	},
	{
		id: 110,
		name: "Economics",
		university: "MacEwan University",
		location: "Edmonton, AB",
		degreeType: "Bachelor",
		admissionRate: 40,
		deadline: "2024-11-25",
		url: "https://www.macewan.ca/economics/admissions.png",
		cost: 9500
	},
	{
		id: 111,
		name: "Education",
		university: "MacEwan University",
		location: "Edmonton, AB",
		degreeType: "Bachelor",
		admissionRate: 35,
		deadline: "2025-02-01",
		url: "https://www.macewan.ca/education/apply.png",
		cost: 11000
	},
	{
		id: 112,
		name: "Business Administration",
		university: "University of Calgary",
		location: "Calgary, AB",
		degreeType: "Bachelor",
		admissionRate: 30,
		deadline: "2024-12-15",
		url: "https://ucalgary.ca/sites/default/files/business-admin.jpg",
		cost: 22000
	},
	{
		id: 113,
		name: "Nursing",
		university: "University of Calgary",
		location: "Calgary, AB",
		degreeType: "Bachelor",
		admissionRate: 28,
		deadline: "2025-01-10",
		url: "https://ucalgary.ca/sites/default/files/nursing.jpg",
		cost: 23000
	},
	{
		id: 114,
		name: "Computer Science",
		university: "University of Calgary",
		location: "Calgary, AB",
		degreeType: "Bachelor",
		admissionRate: 35,
		deadline: "2024-12-25",
		url: "https://ucalgary.ca/sites/default/files/computer-science.jpg",
		cost: 24000
	},
	{
		id: 115,
		name: "Psychology",
		university: "University of Calgary",
		location: "Calgary, AB",
		degreeType: "Bachelor",
		admissionRate: 32,
		deadline: "2025-01-20",
		url: "https://ucalgary.ca/sites/default/files/psychology.jpg",
		cost: 21000
	},
	{
		id: 116,
		name: "Biology",
		university: "University of Calgary",
		location: "Calgary, AB",
		degreeType: "Bachelor",
		admissionRate: 27,
		deadline: "2025-01-05",
		url: "https://ucalgary.ca/sites/default/files/biology.jpg",
		cost: 22000
	},
	{
		id: 117,
		name: "Economics",
		university: "University of Calgary",
		location: "Calgary, AB",
		degreeType: "Bachelor",
		admissionRate: 29,
		deadline: "2024-12-18",
		url: "https://ucalgary.ca/sites/default/files/economics.jpg",
		cost: 22500
	},
	{
		id: 118,
		name: "Education",
		university: "University of Calgary",
		location: "Calgary, AB",
		degreeType: "Bachelor",
		admissionRate: 30,
		deadline: "2025-02-01",
		url: "https://ucalgary.ca/sites/default/files/education.jpg",
		cost: 21500
	}
	

];

export default ProgramList;
