const ProgramList = [
        { 
                id: 1, 
                name: 'Computer Science', 
                university: 'University of Victoria', 
                location: 'Victoria, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 25, 
                deadline: '2024-12-01', 
                url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg', 
                cost: 22000 // Tuition + living costs for Victoria, BC (Bachelor's)
        },
        { 
                id: 2, 
                name: 'Business Administration', 
                university: 'University of British Columbia', 
                location: 'Vancouver, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 35, 
                deadline: '2024-11-15', 
                url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg', 
                cost: 25000 // Vancouver has higher living costs (Bachelor's)
        },
        { 
                id: 3, 
                name: 'Environmental Science', 
                university: 'Thompson Rivers University', 
                location: 'Kamloops, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 40, 
                deadline: '2024-10-30', 
                url: 'https://universitystudy.ca/wp-content/uploads/2013/08/Thompson-Rivers_banner_web-960x.jpg', 
                cost: 20000 // Lower living costs in Kamloops, BC (Bachelor's)
        },
        { 
                id: 4, 
                name: 'Mechanical Engineering', 
                university: 'University of Calgary', 
                location: 'Calgary, AB', 
                degreeType: 'Bachelor', 
                admissionRate: 30, 
                deadline: '2024-12-05', 
                url: 'https://ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba', 
                cost: 23000 // Moderate costs for Calgary, AB (Bachelor's)
        },
        { 
                id: 5, 
                name: 'Psychology', 
                university: 'University of Alberta', 
                location: 'Edmonton, AB', 
                degreeType: 'Bachelor', 
                admissionRate: 45, 
                deadline: '2024-11-30', 
                url: 'https://images.shiksha.com/mediadata/images/1533646004phpFUNLK4.jpeg', 
                cost: 22000 // Moderate costs for Edmonton, AB (Bachelor's)
        },
        { 
                id: 6, 
                name: 'Law', 
                university: 'University of British Columbia', 
                location: 'Vancouver, BC', 
                degreeType: 'Master', 
                admissionRate: 20, 
                deadline: '2024-12-20', 
                url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg', 
                cost: 30000 // Higher cost for Master's in Vancouver, BC
        },
        { 
                id: 7, 
                name: 'Biology', 
                university: 'Simon Fraser University', 
                location: 'Burnaby, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 50, 
                deadline: '2024-11-25', 
                url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_rwTmM_uiGLg5DXBmRPXg72gqQ8FpEq8Ig&s', 
                cost: 24000 // Burnaby, BC, moderate cost (Bachelor's)
        },
        { 
                id: 8, 
                name: 'Environmental Engineering', 
                university: 'University of Calgary', 
                location: 'Calgary, AB', 
                degreeType: 'Bachelor', 
                admissionRate: 35, 
                deadline: '2024-12-10', 
                url: 'https://ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba', 
                cost: 23000 // Calgary, AB (Bachelor's)
        },
        { 
                id: 9, 
                name: 'Nursing', 
                university: 'University of British Columbia', 
                location: 'Vancouver, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 20, 
                deadline: '2024-12-15', 
                url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg', 
                cost: 27000 // Nursing costs slightly higher in Vancouver, BC (Bachelor's)
        },
        { 
                id: 10, 
                name: 'Finance', 
                university: 'University of Alberta', 
                location: 'Edmonton, AB', 
                degreeType: 'Bachelor', 
                admissionRate: 30, 
                deadline: '2024-11-20', 
                url: 'https://images.shiksha.com/mediadata/images/1533646004phpFUNLK4.jpeg', 
                cost: 22000 // Moderate costs for Edmonton, AB (Bachelor's)
        },
        { 
                id: 11, 
                name: 'Engineering Physics', 
                university: 'University of Victoria', 
                location: 'Victoria, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 35, 
                deadline: '2024-11-25', 
                url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg', 
                cost: 23000 // Higher for engineering program in Victoria, BC
        },
        { 
                id: 12, 
                name: 'Biochemistry', 
                university: 'University of Calgary', 
                location: 'Calgary, AB', 
                degreeType: 'Bachelor', 
                admissionRate: 40, 
                deadline: '2024-12-10', 
                url: 'https://ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba', 
                cost: 23000 // Calgary, AB (Bachelor's)
        },
        { 
                id: 13, 
                name: 'Arts and Sciences', 
                university: 'University of British Columbia Okanagan', 
                location: 'Kelowna, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 50, 
                deadline: '2024-11-30', 
                url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg', 
                cost: 21000 // Kelowna is slightly cheaper (Bachelor's)
        },
        { 
                id: 14, 
                name: 'Computer Science', 
                university: 'University of Alberta', 
                location: 'Edmonton, AB', 
                degreeType: 'Master', 
                admissionRate: 30, 
                deadline: '2024-12-15', 
                url: 'https://images.shiksha.com/mediadata/images/1533646004phpFUNLK4.jpeg', 
                cost: 28000 // Higher cost for Master's program in Edmonton, AB
        },
        { 
                id: 15, 
                name: 'Environmental Studies', 
                university: 'Simon Fraser University', 
                location: 'Burnaby, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 45, 
                deadline: '2024-11-20', 
                url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_rwTmM_uiGLg5DXBmRPXg72gqQ8FpEq8Ig&s', 
                cost: 24000 // Burnaby, BC, moderate cost
        },
        { 
                id: 16, 
                name: 'Political Science', 
                university: 'University of Victoria', 
                location: 'Victoria, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 45, 
                deadline: '2024-12-15', 
                url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg', 
                cost: 22000 // Victoria, BC, moderate cost
        },
        { 
                id: 17, 
                name: 'Sociology', 
                university: 'University of Calgary', 
                location: 'Calgary, AB', 
                degreeType: 'Bachelor', 
                admissionRate: 25, 
                deadline: '2024-11-20', 
                url: 'https://www.ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba', 
                cost: 23000 // Calgary, AB, moderate cost
        },
        { 
                id: 18, 
                name: 'Mathematics', 
                university: 'University of British Columbia Okanagan', 
                location: 'Kelowna, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 35, 
                deadline: '2024-12-05', 
                url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg', 
                cost: 21000 // Kelowna, BC, slightly lower cost
        },
        { 
                id: 19, 
                name: 'Economics', 
                university: 'University of Alberta', 
                location: 'Edmonton, AB', 
                degreeType: 'Bachelor', 
                admissionRate: 40, 
                deadline: '2024-11-25', 
                url: 'https://images.shiksha.com/mediadata/images/1533646004phpFUNLK4.jpeg', 
                cost: 22000 // Edmonton, AB, moderate cost
        },
        { 
                id: 20, 
                name: 'Environmental Engineering', 
                university: 'University of British Columbia', 
                location: 'Vancouver, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 30, 
                deadline: '2024-11-30', 
                url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg', 
                cost: 27000 // Vancouver, BC, higher cost
        },
        { 
                id: 21, 
                name: 'Film Studies', 
                university: 'Simon Fraser University', 
                location: 'Burnaby, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 45, 
                deadline: '2024-12-15', 
                url: 'https://www.sfu.ca/content/sfu/sfucommunity/woodwards/photo-gallery/jcr:content/main_content/image_0.img.960.auto.jpg/1634310628497.jpg', 
                cost: 24000 // Burnaby, BC, moderate cost
        },
        { 
                id: 22, 
                name: 'History', 
                university: 'University of Calgary', 
                location: 'Calgary, AB', 
                degreeType: 'Bachelor', 
                admissionRate: 25, 
                deadline: '2024-11-20', 
                url: 'https://www.ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba', 
                cost: 23000 // Calgary, AB, moderate cost
        },
        { 
                id: 23, 
                name: 'Philosophy', 
                university: 'University of British Columbia Okanagan', 
                location: 'Kelowna, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 35, 
                deadline: '2024-12-05', 
                url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg', 
                cost: 21000 // Kelowna, BC, slightly lower cost
        },
        { 
                id: 24, 
                name: 'Education', 
                university: 'University of Alberta', 
                location: 'Edmonton, AB', 
                degreeType: 'Bachelor', 
                admissionRate: 40, 
                deadline: '2024-11-25', 
                url: 'https://images.shiksha.com/mediadata/images/1533646004phpFUNLK4.jpeg', 
                cost: 22000 // Edmonton, AB, moderate cost
        },
        { 
                id: 25, 
                name: 'Geography', 
                university: 'University of British Columbia', 
                location: 'Vancouver, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 30, 
                deadline: '2024-11-30', 
                url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg', 
                cost: 27000 // Vancouver, BC, higher cost
        },
        { 
                id: 26, 
                name: 'Indigenous Studies', 
                university: 'University of Victoria', 
                location: 'Victoria, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 40, 
                deadline: '2024-12-05', 
                url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg', 
                cost: 22000 // Victoria, BC, moderate cost
        },
        { 
                id: 27, 
                name: 'Computer Science', 
                university: 'University of Northern British Columbia', 
                location: 'Prince George, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 25, 
                deadline: '2024-12-01', 
                url: 'https://www.unbc.ca/sites/default/files/styles/listed_image/public/featured-link/dsc2878crop.jpg.webp?itok=rzZEleNT', 
                cost: 20000 // Prince George, BC, lower cost
        },
        { 
                id: 28, 
                name: 'Anthropology', 
                university: 'University of British Columbia Okanagan', 
                location: 'Kelowna, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 35, 
                deadline: '2024-12-05', 
                url: 'https://www.ubc.ca/_assets/img/our-campuses/ubco-aerials-our-campus_1920x700.jpg', 
                cost: 21000 // Kelowna, BC, slightly lower cost
        },
        { 
                id: 29, 
                name: 'Sustainable Energy Engineering', 
                university: 'Simon Fraser University', 
                location: 'Burnaby, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 30, 
                deadline: '2024-12-01', 
                url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_rwTmM_uiGLg5DXBmRPXg72gqQ8FpEq8Ig&s', 
                cost: 24000 // Burnaby, BC, moderate cost
        },
        { 
                id: 30, 
                name: 'Physics', 
                university: 'University of Calgary', 
                location: 'Calgary, AB', 
                degreeType: 'Bachelor', 
                admissionRate: 45, 
                deadline: '2024-11-25', 
                url: 'https://www.ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba', 
                cost: 23000 // Calgary, AB, moderate cost
        },
        { 
                id: 31, 
                name: 'Architecture', 
                university: 'University of British Columbia', 
                location: 'Vancouver, BC', 
                degreeType: 'Master', 
                admissionRate: 25, 
                deadline: '2025-01-20', 
                url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg', 
                cost: 32000 // Higher cost for Master's in Vancouver, BC
        },
        { 
                id: 32, 
                name: 'Human Resource Management', 
                university: 'University of Alberta', 
                location: 'Edmonton, AB', 
                degreeType: 'Bachelor', 
                admissionRate: 40, 
                deadline: '2024-12-05', 
                url: 'https://images.shiksha.com/mediadata/images/1533646004phpFUNLK4.jpeg', 
                cost: 22000 // Moderate cost for Bachelor's in Edmonton, AB
        },
        { 
                id: 33, 
                name: 'Environmental Science', 
                university: 'University of Calgary', 
                location: 'Calgary, AB', 
                degreeType: 'Master', 
                admissionRate: 30, 
                deadline: '2025-01-10', 
                url: 'https://www.ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba', 
                cost: 30000 // Higher cost for Master's in Calgary, AB
        },
        { 
                id: 34, 
                name: 'Political Economy', 
                university: 'University of Victoria', 
                location: 'Victoria, BC', 
                degreeType: 'Master', 
                admissionRate: 20, 
                deadline: '2025-01-30', 
                url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg', 
                cost: 28000 // Higher cost for Master's in Victoria, BC
        },
        { 
                id: 35, 
                name: 'Public Relations', 
                university: 'Royal Roads University', 
                location: 'Victoria, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 50, 
                deadline: '2024-11-30', 
                url: 'https://cdn.prod.website-files.com/667c59abb9df9789d17407a6/667dd6863400fe779b562af4_UNIVERSITY-GUIDEBOOK-2022-ROYAL-ROADS-01-1.jpeg', 
                cost: 21000 // Lower cost for Bachelor's in Victoria, BC
        },
        { 
                id: 36, 
                name: 'Data Science', 
                university: 'University of British Columbia', 
                location: 'Vancouver, BC', 
                degreeType: 'Master', 
                admissionRate: 15, 
                deadline: '2025-02-15', 
                url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg', 
                cost: 33000 // High cost for Data Science Master's in Vancouver, BC
        },
        { 
                id: 37, 
                name: 'Sociology', 
                university: 'University of Northern British Columbia', 
                location: 'Prince George, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 40, 
                deadline: '2024-12-10', 
                url: 'https://www.unbc.ca/sites/default/files/styles/listed_image/public/featured-link/dsc2878crop.jpg.webp?itok=rzZEleNT', 
                cost: 20000 // Lower cost for Bachelor's in Prince George, BC
        },
        { 
                id: 38, 
                name: 'Nursing', 
                university: 'Mount Royal University', 
                location: 'Calgary, AB', 
                degreeType: 'Bachelor', 
                admissionRate: 30, 
                deadline: '2024-11-15', 
                url: 'https://www.unbc.ca/sites/default/files/styles/listed_image/public/featured-link/dsc2878crop.jpg.webp?itok=rzZEleNT', 
                cost: 23000 // Moderate cost for Nursing Bachelor's in Calgary, AB
        },
        { 
                id: 39, 
                name: 'Criminology', 
                university: 'Simon Fraser University', 
                location: 'Burnaby, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 35, 
                deadline: '2024-12-01', 
                url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi_rwTmM_uiGLg5DXBmRPXg72gqQ8FpEq8Ig&s', 
                cost: 24000 // Moderate cost for Bachelor's in Burnaby, BC
        },
        { 
                id: 40, 
                name: 'Environmental Design', 
                university: 'University of Calgary', 
                location: 'Calgary, AB', 
                degreeType: 'Master', 
                admissionRate: 20, 
                deadline: '2025-01-25', 
                url: 'https://www.ucalgary.ca/sites/default/files/styles/ucws_hero_cta_desktop/public/2019-10/mainCampus-hero_1.jpg?itok=NfR3C6Ba', 
                cost: 31000 // Higher cost for Environmental Design Master's in Calgary, AB
        },
        { 
                id: 41, 
                name: 'Agriculture', 
                university: 'University of British Columbia', 
                location: 'Vancouver, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 25, 
                deadline: '2024-11-20', 
                url: 'https://www.ubc.ca/_assets/img/aerial-main-mall-800x253.jpg', 
                cost: 27000 // Higher cost for Bachelor's in Vancouver, BC
        },
        { 
                id: 42, 
                name: 'Graphic Design', 
                university: 'Emily Carr University of Art + Design', 
                location: 'Vancouver, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 30, 
                deadline: '2024-12-01', 
                url: 'https://dsai.ca/wp-content/uploads/Emily-Carr-Hero.jpg', 
                cost: 26000 // Moderate cost for Bachelor's in Vancouver, BC
        },
        { 
                id: 43, 
                name: 'Music Composition', 
                university: 'University of Alberta', 
                location: 'Edmonton, AB', 
                degreeType: 'Bachelor', 
                admissionRate: 40, 
                deadline: '2024-11-30', 
                url: 'https://images.shiksha.com/mediadata/images/1533646004phpFUNLK4.jpeg', 
                cost: 22000 // Moderate cost for Bachelor's in Edmonton, AB
        },
        { 
                id: 44, 
                name: 'Linguistics', 
                university: 'University of Victoria', 
                location: 'Victoria, BC', 
                degreeType: 'Bachelor', 
                admissionRate: 35, 
                deadline: '2024-12-10', 
                url: 'https://cms.macleans.ca/wp-content/uploads/2018/04/MACU01_BC_VICTORIA02.jpg', 
                cost: 22000 // Moderate cost for Bachelor's in Victoria, BC
        }
        ];

export default ProgramList;